<?php

/**
 * Implementing hook_theme
 */
function santa_theme() {
  // Globe Search
  $theme['home_slider'] = [
    'variables' => [
      'data' => [],
			'#attached' => [
				'library' => 'santa/home-slider',
			]
    ],
  ];
	
	// XML 
  $theme['xml_upload'] = [
    'variables' => [
      'xml_upload_form' => [],
      'xml_listing_form' => [],
    ],
  ];

  return $theme;
}

/**
 * Implements hook_preprocess_page().
 */
function santa_preprocess_page(&$variables) {
  
}

/**
 * Implements hook_preprocess_node().
 */
function santa_preprocess_node(&$variables) {
	if($variables['node']->getType() == 'business_permits') {
		$nid = $variables['node']->id();
		if($variables['node']->hasField('field_sample_xml')) {
			$fid = $variables['node']->get('field_sample_xml')->getValue()[0]['target_id'];
		}
		$current_user = \Drupal::currentUser();
		$userRole = $current_user->getRoles();
		
		$xmlUploadForm = '';
		if(in_array('super_admin', $userRole) || in_array('administrator', $userRole)) {
			$xmlUploadForm = \Drupal::formBuilder()->getForm('Drupal\santa\Form\XmlUploadForm', $nid, $fid);
		}
		$xmlListingForm = \Drupal::formBuilder()->getForm('Drupal\santa\Form\XmlListingForm', $nid, $fid);
		
		$variables['xmlUploadForm'] = $xmlUploadForm;
		$variables['xmlListingForm'] = $xmlListingForm;
		
		$variables['#attached']['library'][] = 'santa/datatables';
    $variables['#attached']['library'][] = 'santa/datatables_core';
	}
}

/**
 * Implementing hook_preprocess_block
 */
function santa_preprocess_block(&$variables) {
  if (strpos($variables['content']['body'][0]['#text'], '{{ search_form }}') !== false) {
    $block = \Drupal\block\Entity\Block::load('santacity_search');
    $searchForm = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block);
    $searchForm = render($searchForm);
    $variables['content']['body'][0]['#text'] = str_replace('{{ search_form }}', $searchForm, $variables['content']['body'][0]['#text']);
  }

  if (strpos($variables['content']['body'][0]['#text'], '{{ contact_form }}') !== false) {
    /*
    $webform = \Drupal::entityTypeManager()->getStorage('webform')->load('contact');
    $view_builder = \Drupal::service('entity_type.manager')->getViewBuilder('webform');
    $build = $view_builder->view($webform);
    */

    $webform = \Drupal::entityTypeManager()->getStorage('webform')->load('help');
    $webform = $webform->getSubmissionForm();
    $webform = render($webform);
    $variables['content']['body'][0]['#text'] = str_replace('{{ contact_form }}', $webform, $variables['content']['body'][0]['#text']);
  }

  return $build;
}

/**
 * Implementing hook_preprocess_field
 */
function santa_preprocess_field(&$variables, $hook) {


}

/**
 * Implements hook_cronapi().
 */
function santa_cron() {
	dpm(123);
  /* $nids = \Drupal::entityQuery('node')->condition('type','my_custom_type')->execute();
	$nodes =  \Drupal\node\Entity\Node::loadMultiple($nids);
	
	foreach ($nodes as $node) {
		$node->setPublished(false);
		$node->save();
	}
	 */
	
	$eventNodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['type' => 'events']);
  foreach ($eventNodes as $eventNode) {
		dpm($eventNode->get('field_start_date')->getValue());
		
    // $eventNode->setPublished(false);
    // $eventNode->save();
  }
	
	// New Cotent Type
	$newsNodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['type' => 'news']);
  foreach ($newsNodes as $newsNode) {
		dpm($newsNode->get('field_news_date')->getValue());
    // $newsNode->setPublished(false);
    // $newsNode->save();
  }
}

/**
 * The callback for the cron job,
 */
function event_expire_job($job) {
	
}