<?php

/**
 * @file
 * Contains time_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function time_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the time_field module.
    case 'help.page.time_field':
      $output = '';
      $output .= '<h3>' . t('') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}